# Generated by Django 2.2 on 2019-04-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0003_auto_20190331_0854'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='tracker',
        ),
    ]
