# Generated by Django 2.2 on 2019-04-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0004_auto_20190411_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
