# Generated by Django 2.2 on 2019-04-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0005_userinfo_videofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='videofile',
        ),
    ]
