# Generated by Django 2.2 on 2019-04-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0011_auto_20190425_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(blank=True, default='input/img/unknown.jpg', upload_to='profile_image'),
        ),
    ]
