# Generated by Django 2.2 on 2019-04-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0013_auto_20190425_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(blank=True, default='C:/Users/MyPc/Desktop/Tracker/input/static/input/img/unknown.jpg', upload_to='profile_image'),
        ),
    ]
