# Generated by Django 2.2 on 2019-04-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0014_auto_20190425_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(blank=True, default='unknown.jpg', upload_to='profile_image'),
        ),
    ]
