# Generated by Django 2.2 on 2019-04-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0016_auto_20190425_1548'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='tracker',
        ),
    ]
