# Generated by Django 2.2 on 2019-04-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0018_auto_20190425_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(blank=True, default='aravind.jpg', upload_to='profile_image'),
        ),
    ]
