# Generated by Django 2.2 on 2019-04-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0021_auto_20190428_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='process',
            new_name='processed',
        ),
    ]
