# Generated by Django 2.2 on 2019-04-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0022_auto_20190428_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='processed',
        ),
    ]
