# Generated by Django 2.2 on 2019-04-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0023_remove_file_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filepath',
            field=models.FileField(null=True, upload_to='files/', verbose_name=''),
        ),
    ]
