# Generated by Django 2.2 on 2019-04-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0024_auto_20190428_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='processed',
            field=models.IntegerField(default=0),
        ),
    ]
